package lib

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Foo) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "FuncName":
			z.FuncName, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "FuncName")
				return
			}
		case "Request":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Request")
				return
			}
			if z.Request == nil {
				z.Request = make(map[string]string, zb0002)
			} else if len(z.Request) > 0 {
				for key := range z.Request {
					delete(z.Request, key)
				}
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				var za0002 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Request")
					return
				}
				za0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Request", za0001)
					return
				}
				z.Request[za0001] = za0002
			}
		case "Response":
			var zb0003 uint32
			zb0003, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Response")
				return
			}
			if z.Response == nil {
				z.Response = make(map[string]interface{}, zb0003)
			} else if len(z.Response) > 0 {
				for key := range z.Response {
					delete(z.Response, key)
				}
			}
			for zb0003 > 0 {
				zb0003--
				var za0003 string
				var za0004 interface{}
				za0003, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Response")
					return
				}
				za0004, err = dc.ReadIntf()
				if err != nil {
					err = msgp.WrapError(err, "Response", za0003)
					return
				}
				z.Response[za0003] = za0004
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Foo) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "FuncName"
	err = en.Append(0x83, 0xa8, 0x46, 0x75, 0x6e, 0x63, 0x4e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.FuncName)
	if err != nil {
		err = msgp.WrapError(err, "FuncName")
		return
	}
	// write "Request"
	err = en.Append(0xa7, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Request)))
	if err != nil {
		err = msgp.WrapError(err, "Request")
		return
	}
	for za0001, za0002 := range z.Request {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "Request")
			return
		}
		err = en.WriteString(za0002)
		if err != nil {
			err = msgp.WrapError(err, "Request", za0001)
			return
		}
	}
	// write "Response"
	err = en.Append(0xa8, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Response)))
	if err != nil {
		err = msgp.WrapError(err, "Response")
		return
	}
	for za0003, za0004 := range z.Response {
		err = en.WriteString(za0003)
		if err != nil {
			err = msgp.WrapError(err, "Response")
			return
		}
		err = en.WriteIntf(za0004)
		if err != nil {
			err = msgp.WrapError(err, "Response", za0003)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Foo) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "FuncName"
	o = append(o, 0x83, 0xa8, 0x46, 0x75, 0x6e, 0x63, 0x4e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.FuncName)
	// string "Request"
	o = append(o, 0xa7, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74)
	o = msgp.AppendMapHeader(o, uint32(len(z.Request)))
	for za0001, za0002 := range z.Request {
		o = msgp.AppendString(o, za0001)
		o = msgp.AppendString(o, za0002)
	}
	// string "Response"
	o = append(o, 0xa8, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65)
	o = msgp.AppendMapHeader(o, uint32(len(z.Response)))
	for za0003, za0004 := range z.Response {
		o = msgp.AppendString(o, za0003)
		o, err = msgp.AppendIntf(o, za0004)
		if err != nil {
			err = msgp.WrapError(err, "Response", za0003)
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Foo) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "FuncName":
			z.FuncName, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FuncName")
				return
			}
		case "Request":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Request")
				return
			}
			if z.Request == nil {
				z.Request = make(map[string]string, zb0002)
			} else if len(z.Request) > 0 {
				for key := range z.Request {
					delete(z.Request, key)
				}
			}
			for zb0002 > 0 {
				var za0001 string
				var za0002 string
				zb0002--
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Request")
					return
				}
				za0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Request", za0001)
					return
				}
				z.Request[za0001] = za0002
			}
		case "Response":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Response")
				return
			}
			if z.Response == nil {
				z.Response = make(map[string]interface{}, zb0003)
			} else if len(z.Response) > 0 {
				for key := range z.Response {
					delete(z.Response, key)
				}
			}
			for zb0003 > 0 {
				var za0003 string
				var za0004 interface{}
				zb0003--
				za0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Response")
					return
				}
				za0004, bts, err = msgp.ReadIntfBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Response", za0003)
					return
				}
				z.Response[za0003] = za0004
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Foo) Msgsize() (s int) {
	s = 1 + 9 + msgp.StringPrefixSize + len(z.FuncName) + 8 + msgp.MapHeaderSize
	if z.Request != nil {
		for za0001, za0002 := range z.Request {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.StringPrefixSize + len(za0002)
		}
	}
	s += 9 + msgp.MapHeaderSize
	if z.Response != nil {
		for za0003, za0004 := range z.Response {
			_ = za0004
			s += msgp.StringPrefixSize + len(za0003) + msgp.GuessSize(za0004)
		}
	}
	return
}
